# Generated by moon2nix. Do not edit.
{
  "main" = "example/hello/main";
  "roots" = [
    "@build@/example/hello/main/main.exe"
  ];
  "target" = "native";
  "actions" = [
    {
      "id" = "@build@/runtime-env.o";
      "inputs" = [
        "@toolchain@/lib/runtime/env.c"
      ];
      "command" = {
        "cwd" = null;
        "argv" = [
          "cc"
          "-o"
          "@build@/runtime-env.o"
          "-I@toolchain@/include"
          "-c"
          "-fwrapv"
          "-fno-strict-aliasing"
          "-O2"
          "-DMOONBIT_ALLOW_STACKTRACE"
          "@toolchain@/lib/runtime/env.c"
        ];
        "kind" = "exec";
      };
      "outputs" = [
        "@build@/runtime-env.o"
      ];
    }
    {
      "id" = "@build@/runtime-utf.o";
      "inputs" = [
        "@toolchain@/lib/runtime/utf.c"
      ];
      "command" = {
        "cwd" = null;
        "argv" = [
          "cc"
          "-o"
          "@build@/runtime-utf.o"
          "-I@toolchain@/include"
          "-c"
          "-fwrapv"
          "-fno-strict-aliasing"
          "-O2"
          "-DMOONBIT_ALLOW_STACKTRACE"
          "@toolchain@/lib/runtime/utf.c"
        ];
        "kind" = "exec";
      };
      "outputs" = [
        "@build@/runtime-utf.o"
      ];
    }
    {
      "id" = "@build@/runtime-runtime.o";
      "inputs" = [
        "@toolchain@/lib/runtime/runtime.c"
      ];
      "command" = {
        "cwd" = null;
        "argv" = [
          "cc"
          "-o"
          "@build@/runtime-runtime.o"
          "-I@toolchain@/include"
          "-c"
          "-fwrapv"
          "-fno-strict-aliasing"
          "-O2"
          "-DMOONBIT_ALLOW_STACKTRACE"
          "@toolchain@/lib/runtime/runtime.c"
        ];
        "kind" = "exec";
      };
      "outputs" = [
        "@build@/runtime-runtime.o"
      ];
    }
    {
      "id" = "@build@/runtime-sync_io.o";
      "inputs" = [
        "@toolchain@/lib/runtime/sync_io.c"
      ];
      "command" = {
        "cwd" = null;
        "argv" = [
          "cc"
          "-o"
          "@build@/runtime-sync_io.o"
          "-I@toolchain@/include"
          "-c"
          "-fwrapv"
          "-fno-strict-aliasing"
          "-O2"
          "-DMOONBIT_ALLOW_STACKTRACE"
          "@toolchain@/lib/runtime/sync_io.c"
        ];
        "kind" = "exec";
      };
      "outputs" = [
        "@build@/runtime-sync_io.o"
      ];
    }
    {
      "id" = "@build@/runtime-backtrace.o";
      "inputs" = [
        "@toolchain@/lib/runtime/backtrace.c"
      ];
      "command" = {
        "cwd" = null;
        "argv" = [
          "cc"
          "-o"
          "@build@/runtime-backtrace.o"
          "-I@toolchain@/include"
          "-c"
          "-fwrapv"
          "-fno-strict-aliasing"
          "-O2"
          "-DMOONBIT_ALLOW_STACKTRACE"
          "@toolchain@/lib/runtime/backtrace.c"
        ];
        "kind" = "exec";
      };
      "outputs" = [
        "@build@/runtime-backtrace.o"
      ];
    }
    {
      "id" = "@build@/example/hello/main/main.c";
      "inputs" = [
        "@toolchain@/lib/core/_build/native/release/bundle/abort/abort.core"
        "@toolchain@/lib/core/_build/native/release/bundle/core.core"
        "@build@/example/support/support.core"
        "@build@/example/hello/lib/lib.core"
        "@build@/example/hello/main/main.core"
      ];
      "command" = {
        "cwd" = null;
        "argv" = [
          "moonc"
          "link-core"
          "@toolchain@/lib/core/_build/native/release/bundle/abort/abort.core"
          "@toolchain@/lib/core/_build/native/release/bundle/core.core"
          "@build@/example/support/support.core"
          "@build@/example/hello/lib/lib.core"
          "@build@/example/hello/main/main.core"
          "-main"
          "example/hello/main"
          "-o"
          "@build@/example/hello/main/main.c"
          "-pkg-config-path"
          "@src0@/main/moon.pkg.json"
          "-pkg-sources"
          "example/support:@src1@"
          "-pkg-sources"
          "example/hello/lib:@src0@/lib"
          "-pkg-sources"
          "example/hello/main:@src0@/main"
          "-pkg-sources"
          "moonbitlang/core:@toolchain@/lib/core"
          "-target"
          "native"
        ];
        "kind" = "exec";
      };
      "outputs" = [
        "@build@/example/hello/main/main.c"
      ];
    }
    {
      "id" = "@build@/example/hello/lib/lib.core";
      "inputs" = [
        "@src0@/lib/lib.mbt"
        "@build@/example/support/support.core"
      ];
      "command" = {
        "cwd" = null;
        "argv" = [
          "moonc"
          "build-package"
          "@src0@/lib/lib.mbt"
          "-o"
          "@build@/example/hello/lib/lib.core"
          "-pkg"
          "example/hello/lib"
          "-std-path"
          "@toolchain@/lib/core/_build/native/release/bundle"
          "-i"
          "@toolchain@/lib/core/_build/native/release/bundle/prelude/prelude.mi:prelude"
          "-i"
          "@build@/example/support/support.mi:support"
          "-pkg-sources"
          "example/hello/lib:@src0@/lib"
          "-target"
          "native"
          "-all-pkgs"
          "@build@/all_pkgs.json"
        ];
        "kind" = "exec";
      };
      "outputs" = [
        "@build@/example/hello/lib/lib.core"
        "@build@/example/hello/lib/lib.mi"
      ];
    }
    {
      "id" = "@build@/example/hello/main/main.exe";
      "inputs" = [
        "@build@/example/hello/main/main.c"
        "@build@/runtime-env.o"
        "@build@/runtime-utf.o"
        "@build@/runtime-runtime.o"
        "@build@/runtime-sync_io.o"
        "@build@/runtime-backtrace.o"
        "@toolchain@/lib/libbacktrace.a"
        "@toolchain@/lib/libmoonbitrun.o"
      ];
      "command" = {
        "cwd" = null;
        "argv" = [
          "cc"
          "-o"
          "@build@/example/hello/main/main.exe"
          "-I@toolchain@/include"
          "-fwrapv"
          "-fno-strict-aliasing"
          "-O2"
          "@toolchain@/lib/libmoonbitrun.o"
          "@build@/example/hello/main/main.c"
          "@build@/runtime-env.o"
          "@build@/runtime-utf.o"
          "@build@/runtime-runtime.o"
          "@build@/runtime-sync_io.o"
          "@build@/runtime-backtrace.o"
          "-lm"
          "@toolchain@/lib/libbacktrace.a"
        ];
        "kind" = "exec";
      };
      "outputs" = [
        "@build@/example/hello/main/main.exe"
      ];
    }
    {
      "id" = "@build@/example/hello/main/main.core";
      "inputs" = [
        "@src0@/main/main.mbt"
        "@build@/example/hello/lib/lib.core"
      ];
      "command" = {
        "cwd" = null;
        "argv" = [
          "moonc"
          "build-package"
          "@src0@/main/main.mbt"
          "-o"
          "@build@/example/hello/main/main.core"
          "-pkg"
          "example/hello/main"
          "-is-main"
          "-std-path"
          "@toolchain@/lib/core/_build/native/release/bundle"
          "-i"
          "@toolchain@/lib/core/_build/native/release/bundle/prelude/prelude.mi:prelude"
          "-i"
          "@build@/example/hello/lib/lib.mi:lib"
          "-pkg-sources"
          "example/hello/main:@src0@/main"
          "-target"
          "native"
          "-all-pkgs"
          "@build@/all_pkgs.json"
        ];
        "kind" = "exec";
      };
      "outputs" = [
        "@build@/example/hello/main/main.core"
        "@build@/example/hello/main/main.mi"
      ];
    }
    {
      "id" = "@build@/example/support/support.core";
      "inputs" = [
        "@src1@/lib.mbt"
      ];
      "command" = {
        "cwd" = null;
        "argv" = [
          "moonc"
          "build-package"
          "@src1@/lib.mbt"
          "-o"
          "@build@/example/support/support.core"
          "-pkg"
          "example/support"
          "-std-path"
          "@toolchain@/lib/core/_build/native/release/bundle"
          "-i"
          "@toolchain@/lib/core/_build/native/release/bundle/prelude/prelude.mi:prelude"
          "-pkg-sources"
          "example/support:@src1@"
          "-target"
          "native"
          "-all-pkgs"
          "@build@/all_pkgs.json"
          "-w"
          "-a"
        ];
        "kind" = "exec";
      };
      "outputs" = [
        "@build@/example/support/support.core"
        "@build@/example/support/support.mi"
      ];
    }
  ];
  "packages" = [
    {
      "rel" = "lib";
      "root" = "example/hello";
      "artifact" = "@build@/example/hello/lib/lib.mi";
    }
    {
      "rel" = "main";
      "root" = "example/hello";
      "artifact" = "@build@/example/hello/main/main.mi";
    }
    {
      "rel" = "";
      "root" = "example/support";
      "artifact" = "@build@/example/support/support.mi";
    }
  ];
  "platform" = "linux";
  "sourceCount" = 2;
  "schemaVersion" = 1;
}
