# Generated by moon2nix. Do not edit.
{
  "main" = "example/hello/main";
  "roots" = [
    "@build@/example/hello/main/main.wasm"
  ];
  "target" = "wasm-gc";
  "actions" = [
    {
      "id" = "@build@/example/hello/lib/lib.core";
      "inputs" = [
        "@src0@/lib/lib.mbt"
        "@build@/example/support/support.core"
      ];
      "command" = {
        "cwd" = null;
        "argv" = [
          "moonc"
          "build-package"
          "@src0@/lib/lib.mbt"
          "-o"
          "@build@/example/hello/lib/lib.core"
          "-pkg"
          "example/hello/lib"
          "-std-path"
          "@toolchain@/lib/core/_build/wasm-gc/release/bundle"
          "-i"
          "@toolchain@/lib/core/_build/wasm-gc/release/bundle/prelude/prelude.mi:prelude"
          "-i"
          "@build@/example/support/support.mi:support"
          "-pkg-sources"
          "example/hello/lib:@src0@/lib"
          "-target"
          "wasm-gc"
          "-all-pkgs"
          "@build@/all_pkgs.json"
        ];
        "kind" = "exec";
      };
      "outputs" = [
        "@build@/example/hello/lib/lib.core"
        "@build@/example/hello/lib/lib.mi"
      ];
    }
    {
      "id" = "@build@/example/hello/main/main.core";
      "inputs" = [
        "@src0@/main/main.mbt"
        "@build@/example/hello/lib/lib.core"
      ];
      "command" = {
        "cwd" = null;
        "argv" = [
          "moonc"
          "build-package"
          "@src0@/main/main.mbt"
          "-o"
          "@build@/example/hello/main/main.core"
          "-pkg"
          "example/hello/main"
          "-is-main"
          "-std-path"
          "@toolchain@/lib/core/_build/wasm-gc/release/bundle"
          "-i"
          "@toolchain@/lib/core/_build/wasm-gc/release/bundle/prelude/prelude.mi:prelude"
          "-i"
          "@build@/example/hello/lib/lib.mi:lib"
          "-pkg-sources"
          "example/hello/main:@src0@/main"
          "-target"
          "wasm-gc"
          "-all-pkgs"
          "@build@/all_pkgs.json"
        ];
        "kind" = "exec";
      };
      "outputs" = [
        "@build@/example/hello/main/main.core"
        "@build@/example/hello/main/main.mi"
      ];
    }
    {
      "id" = "@build@/example/hello/main/main.wasm";
      "inputs" = [
        "@toolchain@/lib/core/_build/wasm-gc/release/bundle/abort/abort.core"
        "@toolchain@/lib/core/_build/wasm-gc/release/bundle/core.core"
        "@build@/example/support/support.core"
        "@build@/example/hello/lib/lib.core"
        "@build@/example/hello/main/main.core"
      ];
      "command" = {
        "cwd" = null;
        "argv" = [
          "moonc"
          "link-core"
          "@toolchain@/lib/core/_build/wasm-gc/release/bundle/abort/abort.core"
          "@toolchain@/lib/core/_build/wasm-gc/release/bundle/core.core"
          "@build@/example/support/support.core"
          "@build@/example/hello/lib/lib.core"
          "@build@/example/hello/main/main.core"
          "-main"
          "example/hello/main"
          "-o"
          "@build@/example/hello/main/main.wasm"
          "-pkg-config-path"
          "@src0@/main/moon.pkg.json"
          "-pkg-sources"
          "example/support:@src1@"
          "-pkg-sources"
          "example/hello/lib:@src0@/lib"
          "-pkg-sources"
          "example/hello/main:@src0@/main"
          "-pkg-sources"
          "moonbitlang/core:@toolchain@/lib/core"
          "-target"
          "wasm-gc"
        ];
        "kind" = "exec";
      };
      "outputs" = [
        "@build@/example/hello/main/main.wasm"
      ];
    }
    {
      "id" = "@build@/example/support/support.core";
      "inputs" = [
        "@src1@/lib.mbt"
      ];
      "command" = {
        "cwd" = null;
        "argv" = [
          "moonc"
          "build-package"
          "@src1@/lib.mbt"
          "-o"
          "@build@/example/support/support.core"
          "-pkg"
          "example/support"
          "-std-path"
          "@toolchain@/lib/core/_build/wasm-gc/release/bundle"
          "-i"
          "@toolchain@/lib/core/_build/wasm-gc/release/bundle/prelude/prelude.mi:prelude"
          "-pkg-sources"
          "example/support:@src1@"
          "-target"
          "wasm-gc"
          "-all-pkgs"
          "@build@/all_pkgs.json"
          "-w"
          "-a"
        ];
        "kind" = "exec";
      };
      "outputs" = [
        "@build@/example/support/support.core"
        "@build@/example/support/support.mi"
      ];
    }
  ];
  "packages" = [
    {
      "rel" = "lib";
      "root" = "example/hello";
      "artifact" = "@build@/example/hello/lib/lib.mi";
    }
    {
      "rel" = "main";
      "root" = "example/hello";
      "artifact" = "@build@/example/hello/main/main.mi";
    }
    {
      "rel" = "";
      "root" = "example/support";
      "artifact" = "@build@/example/support/support.mi";
    }
  ];
  "platform" = "linux";
  "sourceCount" = 2;
  "schemaVersion" = 1;
}
